FROM ruby:3.3-alpine

RUN apk add --no-cache git
RUN gem install sinatra rackup puma --no-doc

COPY lib/ /sentinel/lib/
COPY bot/ /sentinel/bot/

WORKDIR /sentinel

EXPOSE 3000

CMD ["ruby", "bot/web.rb"]
